name: Release new TrigiDigital Bot version

on:
  push:
    branches: ["main"]

permissions:
  contents: read
  actions: write

jobs:
  build:
    env:
      DATABASE_URL: "postgresql://"
    strategy:
      matrix:
        app: ["builder", "viewer"]
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: trigidigital/bot-${{ matrix.app }}:latest
          cache-from: type=gha,scope=${{ matrix.app }}
          cache-to: type=gha,scope=${{ matrix.app }},mode=max
          build-args: |
            SCOPE=${{ matrix.app }}

