name: Publish @trigidigital/react package to NPM

on:
  push:
    tags:
      - "react-v*"

jobs:
  publish:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      NODE_OPTIONS: "--max-old-space-size=4096"
    steps:
      - uses: actions/checkout@v2
      - uses: oven-sh/setup-bun@v2
      - run: bun install
      - run: bunx turbo build --filter=@trigidigital/react...
      - run: cd packages/embeds/react && bun publish --access public
